# Generated by Django 5.2.17 on 2026-09-12 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lowongan', models.CharField(blank=True, max_length=200)),
                ('resume_text', models.TextField(help_text='Teks resume/skill yang dinilai')),
                ('job_desc_text', models.TextField(help_text='Deskripsi + kualifikasi lowongan')),
                ('compatibility_score', models.FloatField(help_text='Skor kecocokan 0.0–100.0')),
                ('label', models.CharField(choices=[('No Fit', 'No Fit'), ('Potential Fit', 'Potential Fit'), ('Good Fit', 'Good Fit')], help_text='Kategori: No Fit / Potential Fit / Good Fit', max_length=15)),
                ('cosine_raw', models.FloatField(default=0.0, help_text='Nilai cosine similarity mentah (0.0–1.0)')),
                ('matched_skills', models.TextField(blank=True, help_text='Skill yang cocok (pisah koma)')),
                ('missing_skills', models.TextField(blank=True, help_text='Skill yang kurang (pisah koma)')),
                ('skill_match_pct', models.FloatField(default=0.0, help_text='Persentase skill yang cocok (0–100)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pelamar', models.ForeignKey(blank=True, help_text='User pelamar (opsional untuk testing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_matching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil Matching',
                'verbose_name_plural': 'Hasil Matching',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='HasilSmartGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_soal', models.CharField(help_text='Pertanyaan atau judul soal esai', max_length=500)),
                ('jawaban_pelamar', models.TextField(help_text='Jawaban esai pelamar')),
                ('jawaban_ideal', models.TextField(help_text='Jawaban ideal dari HRD')),
                ('score', models.FloatField(help_text='Nilai 0.0–100.0')),
                ('grade', models.CharField(choices=[('A', 'A — Sangat Baik (85–100)'), ('B', 'B — Baik (70–84)'), ('C', 'C — Cukup (55–69)'), ('D', 'D — Kurang (40–54)'), ('E', 'E — Sangat Kurang (< 40)')], max_length=5)),
                ('cosine_raw', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pelamar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_grading', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil Smart Grading',
                'verbose_name_plural': 'Hasil Smart Grading',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
