# Generated by Django 5.2.17 on 2026-09-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilSJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sesi', models.CharField(default='Psikotes SJT', help_text='Nama sesi tes, misal: Psikotes SJT Batch 1', max_length=200)),
                ('jawaban_json', models.TextField(help_text='Jawaban pelamar dalam JSON')),
                ('skor_total', models.FloatField()),
                ('grade_total', models.CharField(choices=[('A', 'A — Sangat Baik (85–100)'), ('B', 'B — Baik (70–84)'), ('C', 'C — Cukup (55–69)'), ('D', 'D — Kurang (40–54)'), ('E', 'E — Sangat Kurang (< 40)')], max_length=5)),
                ('profil_json', models.TextField(blank=True, default='{}')),
                ('rekomendasi', models.TextField(blank=True)),
                ('detail_json', models.TextField(blank=True, default='[]')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pelamar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_sjt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil SJT',
                'verbose_name_plural': 'Hasil SJT',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SoalSJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skenario', models.TextField(help_text='Deskripsi situasi yang dihadapi pelamar')),
                ('kompetensi', models.CharField(choices=[('Teamwork', 'Teamwork'), ('Problem Solving', 'Problem Solving'), ('Communication', 'Communication'), ('Leadership', 'Leadership'), ('Adaptability', 'Adaptability'), ('Time Management', 'Time Management'), ('Integrity', 'Integrity'), ('Customer Focus', 'Customer Focus')], default='Teamwork', help_text='Kompetensi yang diukur oleh soal ini', max_length=50)),
                ('pilihan_json', models.TextField(help_text='Pilihan A-D dalam format JSON (isi lewat admin)')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soal_sjt_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soal SJT',
                'verbose_name_plural': 'Bank Soal SJT',
                'ordering': ['kompetensi', 'dibuat_pada'],
            },
        ),
    ]
